name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build_node_js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

  test_node_js:
    runs-on: ubuntu-latest
    needs: build_node_js
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build_docker_image:
    runs-on: ubuntu-latest
    needs: test_node_js
    if: ${{ success() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/am-israel-hai .

  push_docker_image:
    runs-on: ubuntu-latest
    needs: build_docker_image
    if: github.ref == 'refs/heads/main' && steps.build_docker_image.outputs.image == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/am-israel-hai:latest

  deploy:
    needs: push_docker_image
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yaml
    with:
      ref: ${{ github.ref }}
