name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version-batch }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build_docker_image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/am-israel-hai .
      
      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'  # Only push if on the main branch
        run: docker push ${{ secrets.DOCKER_USERNAME }}/am-israel-hai

  deploy:
    needs: build_docker_image
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yaml
    with:
      ref: ${{ github.ref }}
