name: Deploy

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to platform
        run: echo "Deploying to platform with ref: ${{ inputs.ref }}"
